// Generated by scripts/generate-fixture-modules.mjs. Re-run after adding fixtures.
import fixture0 from "./fixtures/empty/holdings.json";
import fixture1 from "./fixtures/empty/overview.json";
import fixture2 from "./fixtures/empty/series-1Y.json";
import fixture3 from "./fixtures/empty/series-ITD.json";
import fixture4 from "./fixtures/gap/alerts.json";
import fixture5 from "./fixtures/happy/alerts.json";
import fixture6 from "./fixtures/happy/auth-status.json";
import fixture7 from "./fixtures/happy/benchmarks.json";
import fixture8 from "./fixtures/happy/catalogs.json";
import fixture9 from "./fixtures/happy/health.json";
import fixture10 from "./fixtures/happy/holding-1-series-1Y.json";
import fixture11 from "./fixtures/happy/holding-1-series-3Y.json";
import fixture12 from "./fixtures/happy/holding-1-series-5Y.json";
import fixture13 from "./fixtures/happy/holding-1-series-ITD.json";
import fixture14 from "./fixtures/happy/holding-1-transactions.json";
import fixture15 from "./fixtures/happy/holding-1.json";
import fixture16 from "./fixtures/happy/holding-2-series-1Y.json";
import fixture17 from "./fixtures/happy/holding-2-series-3Y.json";
import fixture18 from "./fixtures/happy/holding-2-series-5Y.json";
import fixture19 from "./fixtures/happy/holding-2-series-ITD.json";
import fixture20 from "./fixtures/happy/holding-2-transactions.json";
import fixture21 from "./fixtures/happy/holding-2.json";
import fixture22 from "./fixtures/happy/holding-3-series-1Y.json";
import fixture23 from "./fixtures/happy/holding-3-series-3Y.json";
import fixture24 from "./fixtures/happy/holding-3-series-5Y.json";
import fixture25 from "./fixtures/happy/holding-3-series-ITD.json";
import fixture26 from "./fixtures/happy/holding-3-transactions.json";
import fixture27 from "./fixtures/happy/holding-3.json";
import fixture28 from "./fixtures/happy/holdings.json";
import fixture29 from "./fixtures/happy/import-result.json";
import fixture30 from "./fixtures/happy/login-url.json";
import fixture31 from "./fixtures/happy/overview.json";
import fixture32 from "./fixtures/happy/performance.json";
import fixture33 from "./fixtures/happy/series-1Y.json";
import fixture34 from "./fixtures/happy/series-3Y.json";
import fixture35 from "./fixtures/happy/series-5Y.json";
import fixture36 from "./fixtures/happy/series-ITD.json";
import fixture37 from "./fixtures/happy/sync-result.json";
import fixture38 from "./fixtures/import_errors/import-report.json";
import fixture39 from "./fixtures/import_errors/import-result.json";
import fixture40 from "./fixtures/logged_out/auth-status.json";
import fixture41 from "./fixtures/missing_prices/holding-1.json";
import fixture42 from "./fixtures/missing_prices/holding-2.json";
import fixture43 from "./fixtures/missing_prices/holding-3.json";
import fixture44 from "./fixtures/missing_prices/holdings.json";
import fixture45 from "./fixtures/missing_prices/overview.json";
import fixture46 from "./fixtures/missing_prices/series-1Y.json";
import fixture47 from "./fixtures/missing_prices/series-3Y.json";
import fixture48 from "./fixtures/missing_prices/series-5Y.json";
import fixture49 from "./fixtures/missing_prices/series-ITD.json";
import fixture50 from "./fixtures/negative/overview.json";
import fixture51 from "./fixtures/stale/auth-status.json";
import fixture52 from "./fixtures/unknown_category/benchmarks.json";
import fixture53 from "./fixtures/unknown_category/holding-3.json";
import fixture54 from "./fixtures/unknown_category/holdings.json";

export const fixtureModules: Record<string, unknown> = {
  "./fixtures/empty/holdings.json": fixture0,
  "./fixtures/empty/overview.json": fixture1,
  "./fixtures/empty/series-1Y.json": fixture2,
  "./fixtures/empty/series-ITD.json": fixture3,
  "./fixtures/gap/alerts.json": fixture4,
  "./fixtures/happy/alerts.json": fixture5,
  "./fixtures/happy/auth-status.json": fixture6,
  "./fixtures/happy/benchmarks.json": fixture7,
  "./fixtures/happy/catalogs.json": fixture8,
  "./fixtures/happy/health.json": fixture9,
  "./fixtures/happy/holding-1-series-1Y.json": fixture10,
  "./fixtures/happy/holding-1-series-3Y.json": fixture11,
  "./fixtures/happy/holding-1-series-5Y.json": fixture12,
  "./fixtures/happy/holding-1-series-ITD.json": fixture13,
  "./fixtures/happy/holding-1-transactions.json": fixture14,
  "./fixtures/happy/holding-1.json": fixture15,
  "./fixtures/happy/holding-2-series-1Y.json": fixture16,
  "./fixtures/happy/holding-2-series-3Y.json": fixture17,
  "./fixtures/happy/holding-2-series-5Y.json": fixture18,
  "./fixtures/happy/holding-2-series-ITD.json": fixture19,
  "./fixtures/happy/holding-2-transactions.json": fixture20,
  "./fixtures/happy/holding-2.json": fixture21,
  "./fixtures/happy/holding-3-series-1Y.json": fixture22,
  "./fixtures/happy/holding-3-series-3Y.json": fixture23,
  "./fixtures/happy/holding-3-series-5Y.json": fixture24,
  "./fixtures/happy/holding-3-series-ITD.json": fixture25,
  "./fixtures/happy/holding-3-transactions.json": fixture26,
  "./fixtures/happy/holding-3.json": fixture27,
  "./fixtures/happy/holdings.json": fixture28,
  "./fixtures/happy/import-result.json": fixture29,
  "./fixtures/happy/login-url.json": fixture30,
  "./fixtures/happy/overview.json": fixture31,
  "./fixtures/happy/performance.json": fixture32,
  "./fixtures/happy/series-1Y.json": fixture33,
  "./fixtures/happy/series-3Y.json": fixture34,
  "./fixtures/happy/series-5Y.json": fixture35,
  "./fixtures/happy/series-ITD.json": fixture36,
  "./fixtures/happy/sync-result.json": fixture37,
  "./fixtures/import_errors/import-report.json": fixture38,
  "./fixtures/import_errors/import-result.json": fixture39,
  "./fixtures/logged_out/auth-status.json": fixture40,
  "./fixtures/missing_prices/holding-1.json": fixture41,
  "./fixtures/missing_prices/holding-2.json": fixture42,
  "./fixtures/missing_prices/holding-3.json": fixture43,
  "./fixtures/missing_prices/holdings.json": fixture44,
  "./fixtures/missing_prices/overview.json": fixture45,
  "./fixtures/missing_prices/series-1Y.json": fixture46,
  "./fixtures/missing_prices/series-3Y.json": fixture47,
  "./fixtures/missing_prices/series-5Y.json": fixture48,
  "./fixtures/missing_prices/series-ITD.json": fixture49,
  "./fixtures/negative/overview.json": fixture50,
  "./fixtures/stale/auth-status.json": fixture51,
  "./fixtures/unknown_category/benchmarks.json": fixture52,
  "./fixtures/unknown_category/holding-3.json": fixture53,
  "./fixtures/unknown_category/holdings.json": fixture54,
};
