/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Callback Get */
        get: operations["callback_get_auth_callback_get"];
        put?: never;
        /** Callback */
        post: operations["callback_auth_callback_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login-url": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Login Url */
        get: operations["login_url_auth_login_url_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Status */
        get: operations["status_auth_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/import/csv": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Import Csv Endpoint */
        post: operations["import_csv_endpoint_import_csv_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/portfolio/alerts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Alerts */
        get: operations["alerts_portfolio_alerts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/portfolio/holdings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Holdings */
        get: operations["holdings_portfolio_holdings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/portfolio/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Overview */
        get: operations["overview_portfolio_overview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/portfolio/performance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Performance */
        get: operations["performance_portfolio_performance_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/settings/benchmarks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Benchmarks */
        get: operations["list_benchmarks_settings_benchmarks_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/settings/benchmarks/{instrument_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Put Benchmark */
        put: operations["put_benchmark_settings_benchmarks__instrument_id__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/settings/categories/{instrument_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Put Category */
        put: operations["put_category_settings_categories__instrument_id__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sync */
        post: operations["sync_sync_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AbsoluteReturn */
        AbsoluteReturn: {
            /** Current Value */
            current_value: number;
            /** Gain Inr */
            gain_inr: number;
            /** Gain Pct */
            gain_pct: number | null;
            /** Invested Cost */
            invested_cost: number;
        };
        /** AlertsResponse */
        AlertsResponse: {
            /** Credentials Configured */
            credentials_configured: boolean;
            gap: components["schemas"]["GapAlert"] | null;
            /** Reconcile */
            reconcile: components["schemas"]["ReconcileDiff"][];
            /** Reconcile Message */
            reconcile_message?: string | null;
            /** Token Connected */
            token_connected: boolean;
        };
        /** AllocationSlice */
        AllocationSlice: {
            /** Symbol */
            symbol: string;
            /** Weight */
            weight: number;
        };
        /** AuthStatusResponse */
        AuthStatusResponse: {
            /** Connected */
            connected: boolean;
            /** Credentials Configured */
            credentials_configured: boolean;
            /** Last Sync At */
            last_sync_at: string | null;
            /** Last Trade Append At */
            last_trade_append_at: string | null;
        };
        /** BatchImportResultResponse */
        BatchImportResultResponse: {
            /** Files */
            files: (components["schemas"]["FileImportOkResponse"] | components["schemas"]["FileImportErrResponse"])[];
            /** Summary */
            summary: {
                [key: string]: number;
            };
        };
        /** BenchmarkBody */
        BenchmarkBody: {
            /** Benchmark Index */
            benchmark_index: string;
        };
        /** BenchmarkItem */
        BenchmarkItem: {
            /** Benchmark Index */
            benchmark_index: string;
            /** Instrument Id */
            instrument_id: number;
            /** Instrument Type */
            instrument_type: string;
            /** Mf Category */
            mf_category: string | null;
            /** Needs Category */
            needs_category: boolean;
            /** Source */
            source: string;
            /** Symbol */
            symbol: string;
        };
        /** BenchmarkListResponse */
        BenchmarkListResponse: {
            /** Items */
            items: components["schemas"]["BenchmarkItem"][];
        };
        /** BenchmarkUpdateResponse */
        BenchmarkUpdateResponse: {
            /** Benchmark Index */
            benchmark_index: string;
            /** Instrument Id */
            instrument_id: number;
            /** Source */
            source: string;
        };
        /** Body_import_csv_endpoint_import_csv_post */
        Body_import_csv_endpoint_import_csv_post: {
            /** File */
            file?: string | null;
            /** Files */
            files?: string[] | null;
        };
        /** CategoryBody */
        CategoryBody: {
            /** Category */
            category: string;
        };
        /** CategoryUpdateResponse */
        CategoryUpdateResponse: {
            /** Instrument Id */
            instrument_id: number;
            /** Mf Category */
            mf_category: string | null;
        };
        /** ConnectedResponse */
        ConnectedResponse: {
            /** Connected */
            connected: boolean;
        };
        /** ContributorResponse */
        ContributorResponse: {
            /** Absolute Excess Pp */
            absolute_excess_pp: number | null;
            /** Cagr Excess Pp */
            cagr_excess_pp: number | null;
            /** Symbol */
            symbol: string;
            /** Value */
            value: number | null;
            /** Weight */
            weight: number;
            /** Windows */
            windows: {
                [key: string]: components["schemas"]["WindowMetrics"] | null;
            };
            /** Xirr Excess Pp */
            xirr_excess_pp: number | null;
        };
        /** FileImportErrResponse */
        FileImportErrResponse: {
            /** Action */
            action: string;
            /**
             * Code
             * @enum {string}
             */
            code: "encoding" | "csv_format" | "csv_parse" | "empty";
            /** Errors */
            errors: string[];
            /** Filename */
            filename: string;
            /** Message */
            message: string;
            /**
             * Ok
             * @constant
             */
            ok: false;
        };
        /** FileImportOkResponse */
        FileImportOkResponse: {
            /** Date Max */
            date_max: string | null;
            /** Date Min */
            date_min: string | null;
            /** Existing */
            existing: number;
            /** Filename */
            filename: string;
            /** Financial Years */
            financial_years: string[];
            /** Flagged Rows */
            flagged_rows: string[];
            /**
             * Format
             * @constant
             */
            format: "console_tradebook";
            /** New */
            new: number;
            /**
             * Ok
             * @constant
             */
            ok: true;
            /** Segment Counts */
            segment_counts: {
                [key: string]: number;
            };
        };
        /** GapAlert */
        GapAlert: {
            /** Message */
            message: string;
            /** Suggested From */
            suggested_from: string;
            /** Suggested To */
            suggested_to: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Status */
            status: string;
        };
        /** HoldingResponse */
        HoldingResponse: {
            /** Absolute Excess Pp */
            absolute_excess_pp: number | null;
            /** Absolute Inr */
            absolute_inr: number | null;
            /** Absolute Pct */
            absolute_pct: number | null;
            /** Avg Price */
            avg_price: number;
            /** Benchmark */
            benchmark: string;
            /** Benchmark Return */
            benchmark_return: number | null;
            /** Cagr */
            cagr: number | null;
            /** Cagr Excess Pp */
            cagr_excess_pp: number | null;
            /** Incomplete */
            incomplete: boolean;
            /** Instrument Id */
            instrument_id: number;
            /** Instrument Type */
            instrument_type: string;
            /** Ltp */
            ltp: number | null;
            /** Needs Category */
            needs_category: boolean;
            /** Qty */
            qty: number;
            /** Symbol */
            symbol: string;
            /** Value */
            value: number | null;
            /** Windows */
            windows: {
                [key: string]: components["schemas"]["WindowMetrics"] | null;
            };
            /** Xirr */
            xirr: number | null;
            /** Xirr Excess Pp */
            xirr_excess_pp: number | null;
        };
        /** HoldingsResponse */
        HoldingsResponse: {
            /** Holdings */
            holdings: components["schemas"]["HoldingResponse"][];
        };
        /** ImportBadDetail */
        ImportBadDetail: {
            /** Action */
            action: string;
            /** Errors */
            errors?: string[];
            /** Message */
            message: string;
        };
        /** ImportBadErrorResponse */
        ImportBadErrorResponse: {
            detail: components["schemas"]["ImportBadDetail"];
        };
        /** ImportResultResponse */
        ImportResultResponse: {
            /** Date Max */
            date_max: string | null;
            /** Date Min */
            date_min: string | null;
            /** Existing */
            existing: number;
            /** Financial Years */
            financial_years: string[];
            /** Flagged Rows */
            flagged_rows: string[];
            /**
             * Format
             * @constant
             */
            format: "console_tradebook";
            /** New */
            new: number;
            /** Segment Counts */
            segment_counts: {
                [key: string]: number;
            };
        };
        /** LoginUrlResponse */
        LoginUrlResponse: {
            /** Login Url */
            login_url: string;
        };
        /** OverviewResponse */
        OverviewResponse: {
            absolute: components["schemas"]["AbsoluteReturn"];
            /** Absolute Excess Pp */
            absolute_excess_pp: number | null;
            /** Allocation */
            allocation: components["schemas"]["AllocationSlice"][];
            /** As Of */
            as_of: string;
            /** Benchmark Return */
            benchmark_return: number | null;
            /** Cagr */
            cagr: number | null;
            /** Cagr Excess Pp */
            cagr_excess_pp: number | null;
            /** Incomplete */
            incomplete: boolean;
            /** Total Value */
            total_value: number;
            /** Windows */
            windows: {
                [key: string]: components["schemas"]["WindowMetrics"] | null;
            };
            /** Xirr */
            xirr: number | null;
            /** Xirr Excess Pp */
            xirr_excess_pp: number | null;
        };
        /** PerformanceResponse */
        PerformanceResponse: {
            absolute: components["schemas"]["AbsoluteReturn"];
            /** Absolute Excess Pp */
            absolute_excess_pp: number | null;
            /** Allocation */
            allocation: components["schemas"]["AllocationSlice"][];
            /** As Of */
            as_of: string;
            /** Benchmark Return */
            benchmark_return: number | null;
            /** Cagr */
            cagr: number | null;
            /** Cagr Excess Pp */
            cagr_excess_pp: number | null;
            /** Contributors */
            contributors: components["schemas"]["ContributorResponse"][];
            /**
             * Default Window
             * @enum {string}
             */
            default_window: "ITD" | "1Y" | "3Y" | "5Y";
            /** Holdings */
            holdings: components["schemas"]["HoldingResponse"][];
            /** Incomplete */
            incomplete: boolean;
            /** Total Value */
            total_value: number;
            /** Windows */
            windows: {
                [key: string]: components["schemas"]["WindowMetrics"] | null;
            };
            /** Windows Available */
            windows_available: ("ITD" | "1Y" | "3Y" | "5Y")[];
            /** Xirr */
            xirr: number | null;
            /** Xirr Excess Pp */
            xirr_excess_pp: number | null;
        };
        /** PricesRefreshResponse */
        PricesRefreshResponse: {
            /** Failed */
            failed: string[];
            /** Incomplete */
            incomplete: boolean;
            /** Updated */
            updated: number;
        };
        /** ReconcileDiff */
        ReconcileDiff: {
            /** Delta */
            delta: number;
            /** Holdings Qty */
            holdings_qty: number;
            /** Instrument Id */
            instrument_id: number;
            /** Symbol */
            symbol: string;
            /** Tx Qty */
            tx_qty: number;
        };
        /** RequestTokenBody */
        RequestTokenBody: {
            /** Request Token */
            request_token: string;
        };
        /** SyncResponse */
        SyncResponse: {
            /** Holdings Count */
            holdings_count: number;
            /** Last Sync At */
            last_sync_at: string;
            prices: components["schemas"]["PricesRefreshResponse"];
            /** Trades Appended */
            trades_appended: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** WindowMetrics */
        WindowMetrics: {
            /** Absolute Excess Pp */
            absolute_excess_pp?: number | null;
            /** Absolute Inr */
            absolute_inr?: number | null;
            /** Absolute Pct */
            absolute_pct?: number | null;
            /** Benchmark Return */
            benchmark_return?: number | null;
            /** Cagr */
            cagr?: number | null;
            /** Cagr Excess Pp */
            cagr_excess_pp?: number | null;
            /** Xirr */
            xirr?: number | null;
            /** Xirr Excess Pp */
            xirr_excess_pp?: number | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    callback_get_auth_callback_get: {
        parameters: {
            query: {
                request_token: string;
                status?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConnectedResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    callback_auth_callback_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RequestTokenBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConnectedResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_url_auth_login_url_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginUrlResponse"];
                };
            };
        };
    };
    logout_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConnectedResponse"];
                };
            };
        };
    };
    status_auth_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthStatusResponse"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    import_csv_endpoint_import_csv_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "multipart/form-data": components["schemas"]["Body_import_csv_endpoint_import_csv_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportResultResponse"] | components["schemas"]["BatchImportResultResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportBadErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    alerts_portfolio_alerts_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertsResponse"];
                };
            };
        };
    };
    holdings_portfolio_holdings_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HoldingsResponse"];
                };
            };
        };
    };
    overview_portfolio_overview_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OverviewResponse"];
                };
            };
        };
    };
    performance_portfolio_performance_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PerformanceResponse"];
                };
            };
        };
    };
    list_benchmarks_settings_benchmarks_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BenchmarkListResponse"];
                };
            };
        };
    };
    put_benchmark_settings_benchmarks__instrument_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                instrument_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BenchmarkBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BenchmarkUpdateResponse"];
                };
            };
            /** @description Unknown benchmark index */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Instrument not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    put_category_settings_categories__instrument_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                instrument_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CategoryBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryUpdateResponse"];
                };
            };
            /** @description Instrument not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sync_sync_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyncResponse"];
                };
            };
            /** @description Kite reconnection required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
